# generate smaller figures for demonstration
devpars = { width = 800, height = 600, res = 100}

[[ggs]]
custom = '''
    theme_minimal();
    scale_color_discrete(name="Cromosoma", 
                         breaks=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
                                  "11", "12", "13", "14", "15", "16", "17", "18", "19", 
                                  "20", "21", "22", "X", "Y"),
                         labels=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
                                  "11", "12", "13", "14", "15", "16", "17", "18", "19", 
                                  "20", "21", "22", "X", "Y"));
    xlab("Profundidad Promedio");
    ylab("Calidad del Genotipo Promedio");
'''
